### ISSUE TITLE
Option for custom instance

### ISSUE THREAD

**Issue by vovkkk** [AnkhSquirrel/PipedSwitch#1]
Could you please add an option to set any instance instead of default one?

There are [a plenty of them ](https://github.com/TeamPiped/Piped/wiki/Instances) and they have different availability in different countries, so the preference would mostly depend on geographical location of a user.

For example, 
`https://piped.kavin.rocks/` is not available for me,
but `https://piped.video/` is available 
and `https://pipedapi.kavin.rocks` redirects to `https://piped.video/`

**Comment by AnkhSquirrel** [comment]
Available in v1.1.1, should go live on Firefox soon
